### PR TITLE
Dont stick on concrete egui version.

### PR DESCRIPTION
**Pull request by enomado**
Need ability to dictate egui version from project using it, not library itself

### CODE REVIEW

**Comment by Adanos020** [comment]
I'm not sure about this one. APIs change from version to version, so depending on a wrong one can lead to compile errors. Crates like `egui_extras` or `egui_glow` also depend on a specific version of `egui`.

I need to hear more opinions about this.

**Comment by Adanos020** [comment]
Breaking changes in future versions of egui are the main reason why I'm not convinced we should take this change. It's not our responsibility to support all its versions at the same time. If you need a different version of `egui` than the one used by this library, you can do what you've been doing so far.

I think we should instead expose our `egui` so people can use it like this: `egui_dock::egui` instead of including `egui` as a separate dependency.

**Comment by enomado** [comment]
@Adanos020 Any reason to stick to 0.19 and not ^0.19?

**Comment by Adanos020** [comment]
@enomado According to Cargo reference `0.19` and `^0.19` are equivalent:

image

image

Restricting to 0.19 only would look like this: `=0.19`.

> What change was breaking , as a cause to higher version bound?

I'm talking about _future_ breaking changes that may or may not happen.

**Pull request closed without merging**
