### PR TITLE
Creating a window on tab drag.

### PR DESCRIPTION
**Pull request by Jerrody**

### CODE REVIEW

**Comment by Jerrody** [comment]
I don't understand how to return window to the node.

**Comment by Jerrody** [comment]
Currently, I don't understand how to determine that window is hovering a attachable zone to the node.

But I made a quite not so comfortable implementation of attaching window to the node.
https://user-images.githubusercontent.com/68968657/188318608-3e4e8388-6afc-4d64-a0e9-12792c64662b.mp4

**Comment by g-tejas** [comment]
Hey, could you share the code for this?

**Comment by Jerrody** [comment]
> Hey, could you share the code for this?

Damn, sorry, I can't share you this code, because I deleted it ;_;

**Comment by g-tejas** [comment]
Ahh no worries, I wanted to ask, if I were to create a new Window, wouldn't that require you to pass in the context to the ui function in TabViewer? How do I go about doing that, if I want to have access to the context from within the tabs? (or create a window that is not part of the tabs for example. my code is [here](https://github.com/FURRY-CAPITAL/enigma_machine), if you wanna check it out.

**Pull request closed without merging**
