### PR TITLE
Keyboard focus fixes

### LINKED ISSUE #207: Keyboard focus works with Shift+Tab but not with just the Tab key
**Describe the bug**
Egui allows users to [focus widgets using the keyboard](https://en.wikipedia.org/wiki/Tabbing_navigation), i.e. selecting focusable widgets like buttons, using the Tab key to navigate in forward order or Shift+Tab to navigate in reverse order. However, widgets in an egui_dock tab will only be navigable in this way if the user uses Shift+Tab. Pressing the Tab key does not work.

**To Reproduce**
Replace the `ui.label(format!("Content of {tab}"));` here in the "simple" example with `let _ = ui.button(format!("Content of {tab}"));` and then run it. https://github.com/Adanos020/egui_dock/blob/c3604425943d9c5f922a8b9aba8e5a5b89e785e9/examples/simple.rs#L26

When holding down Shift+Tab, the focus cycles between the buttons inside the tabs.

When holding down the Tab key alone, nothing happens.

**Expected behavior**
When holding down the Tab key, the focus should cycle between the buttons in the reverse of the order that Shift+Tab cycles the buttons in.

**Screenshots**
This is what's supposed to happen when holding Tab, but in reverse order:
screenshot

### PR DESCRIPTION
**Pull request by white-axe**
This pull request closes #207 by fixing the behaviour of keyboard focus when using the Tab key on the keyboard.

I also added highlighting to the buttons in the tab titles when they are focused with the keyboard, and added the ability to change the current tab by focusing it with the keyboard and then pressing Enter or Space.

If you want me to update the changelog, let me know what I should put for the version.

### CODE REVIEW

**Review by Adanos020 — COMMENTED** [review]
Hi, thanks for looking into this and apologies for the radio silence on the issue.

The code looks sensible, I'll give it a proper test soon (it's 2:37am where I'm at now :smile:).

**Comment by Adanos020** [comment]
Switching between widgets with the Tab key seems to work fine.

I noticed that when you try to switch between tabs and their close buttons, it usually takes several presses of the Tab key to get from one tab to the next. I attempted to see if there was something else in focus, and sure enough, the value of `ui.memory(|m| m.focus())` changes with each press of the Tab key, even though the switch isn't visible in the UI.

@white-axe Do you have any ideas what might cause that?

**Comment by white-axe** [comment]
There were some widgets that were requesting focus when they didn't need it.

I couldn't figure out how to prevent the separators from being focused so for completeness I also added the ability to move them with the arrow keys when focused.

**Comment by Adanos020** [comment]
This is a great improvement! One last thing I think would make this near perfect would be to highlight currently focused separators and tabs the same way they're highlighted on mouse hover. Then I think we can merge this.

**Comment by white-axe** [comment]
There's now a visual indication of when an active tab is focused with the keyboard, although it just uses the "focused" tab style because there isn't a unique tab style for tabs that are active and hovered at the same time.

I'm not sure what you mean by highlighting the currently focused separators. I think I already implemented highlighting them when focusing them with the keyboard.

**Comment by Adanos020** [comment]
Hm, highlighted tabs now look exactly the same as the currently focused tab, i.e. one whose body you've last clicked on. 

image

The only exception is when the currently hovered tab is in a node with multiple tabs and it's not the currently selected tab, then it'll have a brighter border. I think all tabs should behave like this, not just "secondary" ones.

image

Now for separators, I think last time I tested I saw the separators wouldn't get highlighted until you attempted to resize one. Although, that might not have actually been the case since now it doesn't behave this way.

**Comment by white-axe** [comment]
Alright, I've added new styles for tabs that are focused with the keyboard.

**Review by Adanos020 — APPROVED** [review]
Looks good, thanks a lot for working on this!

**Pull request merged**
