### PR TITLE
Add egui tiles as alternative in readme

### PR DESCRIPTION
**Pull request by RegenJacob**
It would be nice to list egui_tiles as an alternative 

Here is the [comparision](https://github.com/rerun-io/egui_tiles#comparison-with-egui_dock)

### CODE REVIEW

**Comment by Adanos020** [comment]
I can't see why we would need this. `egui_tiles` was created as an alternative to `egui_dock`, not the other way around.

**Comment by RegenJacob** [comment]
I think it would be nice if we just let users decide what to use and show what's out there

**Comment by RegenJacob** [comment]
I think it would be nice if we just let users decide what to use and show what's out there

**Review by Adanos020 — APPROVED** [review]
I decided to include this section after doing a revision of it.

**Pull request merged**
