### PR TITLE
Refactor `Style`

### LINKED ISSUE #114: Refactor `Style`
**Is your feature request related to a problem? Please describe.**
The `Style` struct has been getting more and more unwieldy, now containing 36 fields and no separation between those describing behaviour and those describing visuals. This is inconsistent with `egui`'s `Style` which has separate `Visuals` and `Interaction` fields, among others.

**Describe the solution you'd like**
Create new structs: `Visuals` and `Interaction`. Where appropriate, create more structs to separate fields by what part of the docking system they affect (tabs, tab bar, separators, etc.).

**Additional context**
I'm also considering deprecating `StyleBuilder` since constructing `Style` can just as easily be done without it:

```rust
// With StyleBuilder
let style = StyleBuilder::from_egui(ui.style())
    .expand_tabs(true)
    .show_name_when_hovered(true)
    .build();

// Without StyleBuilder
let style = Style {
    expand_tabs: true,
    tab_hover_name: true,
    ..Style::from_egui(ui.style())
};
```

This would vastly decrease duplication of code and name discrepancy (as shown in the example above) in the `style` module.

I want to hear other people's feedback before committing to this.

### PR DESCRIPTION
**Pull request by Adanos020**
Closes #114 

I'll wait before merging this to hear feedback from users.

Please let me know if you have any concerns regarding these changes.

### CODE REVIEW

**Comment by Adanos020** [comment]
@lvaroqui I did that this way because that's what egui does as well 🙂

Thanks for taking a look!

**Comment by lvaroqui** [comment]
Looking at egui `Style::interaction` part:
```
pub struct Interaction {
    pub resize_grab_radius_side: f32
    pub resize_grab_radius_corner: f32
    pub show_tooltips_only_when_still: bool
}
```
I feel like the options are not of same kind as what we have in this PR, they won't fundamentally change the behavior of egui, whether it displays certain stuff or not.

egui_dock is more of a widget/container than a full fledged framework. For egui's widgets the behavior is controlled directly in them and their style is controlled by `egui::Style`.

As a user of egui_dock, I wouldn't expect having to look into the style part to discover I can add change the drag behavior, add close button etc...

Then again that's just my two cents, maybe other users will have other inputs!

**Comment by Adanos020** [comment]
@lvaroqui That makes sense, we might actually need to revisit how these settings are fed into `DockArea`. Perhaps turn that struct into a builder?

**Comment by lvaroqui** [comment]
I feel like DockArea already is kind of a Builder kind of API with the `style(&mut self, ...)` `show(self, ...)`, method. The interactions options could simply be fields inside DockArea (grouped into a structure or not).

**Comment by Adanos020** [comment]
Yeah, that's what I'm thinking. I'll experiment with that.

**Comment by lvaroqui** [comment]
Sounds good!!

**Comment by Adanos020** [comment]
I made these and some additional changes, this does indeed feel better now.

**Comment by lvaroqui** [comment]
Looks really nice, I like it a lot!

**Comment by Jerrody** [comment]
Me too, very good decision to rewrite it.

**Pull request merged**
